In [ ]:
                                                   # Data Transformation Assignment

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv('employee_productivity_dataset.csv')
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

In [4]:
#Question 1:- Handele Missing Values(Basic Cleaning)
# Fill missing values using the following:
# Age -> Median
# Salary-> Mean
# Hours_Worked_Score-> Mean
# Performance_Score-> Mean
# Display the datast after handeling missing values.

In [4]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Gender', 'Work_Mode',
       'Join_Date', 'Hours_Worked_Per_Week', 'Projects_Completed',
       'Performance_Score', 'Salary', 'Location'],
      dtype='object')

In [7]:
df['Hours_Worked_Per_Week']

0      40.0
1      38.0
2      45.0
3       NaN
4      50.0
       ...
245    36.0
246    48.0
247    42.0
248     NaN
249    37.0
Name: Hours_Worked_Per_Week, Length: 250, dtype: float64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            250 non-null    object
 1   Name                   250 non-null    object
 2   Department             250 non-null    object
 3   Age                    225 non-null    float64
 4   Gender                 250 non-null    object
 5   Work_Mode              250 non-null    object
 6   Join_Date              250 non-null    object
 7   Hours_Worked_Per_Week  200 non-null    float64
 8   Projects_Completed     250 non-null    int64
 9   Performance_Score      200 non-null    float64
 10  Salary                 225 non-null    float64
 11  Location               250 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 23.6+ KB

In [9]:
df['Age'].isnull().sum()

np.int64(25)

In [12]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [13]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())

In [15]:
df['Hours_Worked_Per_Week']=df['Hours_Worked_Per_Week'].fillna(df['Hours_Worked_Per_Week'].median())

In [16]:
df['Performance_Score']=df['Performance_Score'].fillna(df['Performance_Score'].mean())

In [17]:
df

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune
...,...,...,...,...,...,...,...,...,...,...,...,...
245,E006,Neha Singh,HR,27.0,Female,Remote,01-06-2023,36.0,3,3.9000,42000.000000,Mumbai
246,E007,Rahul Das,Finance,40.0,Male,Onsite,07-07-2019,48.0,8,4.7000,65000.000000,Delhi
247,E008,Pooja Mehta,Marketing,29.0,Female,Hybrid,12-08-2022,42.0,6,4.3000,48000.000000,Bangalore
248,E009,Sameer Khan,IT,31.0,Male,Remote,30-09-2021,41.0,5,4.1000,51000.000000,Pune
249,E010,Kiran Nair,HR,26.0,Female,Onsite,05-10-2023,37.0,4,4.3125,43000.000000,Mumbai

In [18]:
df.isnull().sum()

Employee_ID              0
Name                     0
Department               0
Age                      0
Gender                   0
Work_Mode                0
Join_Date                0
Hours_Worked_Per_Week    0
Projects_Completed       0
Performance_Score        0
Salary                   0
Location                 0
dtype: int64

In [ ]:
# Question 2:- Label Handeling
# Convert these columns into columns into numeric values using Label Encoding:
# Gender
# Department
# Show the updated columns.

In [5]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le=LabelEncoder()

In [21]:
df['Gender']=le.fit_transform(df['Gender'])

In [22]:
df['Department']=le.fit_transform(df['Department'])

In [23]:
df[['Gender','Department']]

     Gender  Department
0         1           2
1         0           1
2         1           0
3         0           2
4         1           3
..      ...         ...
245       0           1
246       1           0
247       0           3
248       1           2
249       0           1

[250 rows x 2 columns]

In [24]:
df

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,2,25.0,1,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,1,30.0,0,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,0,29.0,1,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,2,28.0,0,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,3,35.0,1,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune
...,...,...,...,...,...,...,...,...,...,...,...,...
245,E006,Neha Singh,1,27.0,0,Remote,01-06-2023,36.0,3,3.9000,42000.000000,Mumbai
246,E007,Rahul Das,0,40.0,1,Onsite,07-07-2019,48.0,8,4.7000,65000.000000,Delhi
247,E008,Pooja Mehta,3,29.0,0,Hybrid,12-08-2022,42.0,6,4.3000,48000.000000,Bangalore
248,E009,Sameer Khan,2,31.0,1,Remote,30-09-2021,41.0,5,4.1000,51000.000000,Pune
249,E010,Kiran Nair,1,26.0,0,Onsite,05-10-2023,37.0,4,4.3125,43000.000000,Mumbai

In [ ]:
# Question 3:- One-Hot Encoding
# Apply One-Hot Encoding on:
# Work Mode
# Location
# Display the dtaset and check how many columns are created

In [4]:
df=pd.get_dummies (df,columns=['Work_Mode'],drop_first=True)

In [6]:
df=pd.get_dummies(df,columns=['Location'],drop_first=True)

In [7]:
df

,Employee_ID,Name,Department,Age,Gender,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Work_Mode_Onsite,Work_Mode_Remote,Location_Delhi,Location_Mumbai,Location_Pune
0,E001,Amit Sharma,IT,25.0,Male,15-01-2021,40.0,5,4.5,50000.0,False,True,False,False,True
1,E002,Riya Patel,HR,30.0,Female,15-02-2020,38.0,4,4.0,45000.0,False,False,False,True,False
2,E003,John Mathew,Finance,NaN,Male,10-03-2022,45.0,6,NaN,60000.0,True,False,False,False,False
3,E004,Sneha Joshi,IT,28.0,Female,22-04-2021,NaN,5,4.2,52000.0,False,True,True,False,False
4,E005,Arjun Verma,Marketing,35.0,Male,18-05-2020,50.0,7,4.8,NaN,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,E006,Neha Singh,HR,27.0,Female,01-06-2023,36.0,3,3.9,42000.0,False,True,False,True,False
246,E007,Rahul Das,Finance,40.0,Male,07-07-2019,48.0,8,4.7,65000.0,True,False,True,False,False
247,E008,Pooja Mehta,Marketing,29.0,Female,12-08-2022,42.0,6,4.3,48000.0,False,False,False,False,False
248,E009,Sameer Khan,IT,31.0,Male,30-09-2021,NaN,5,4.1,51000.0,False,True,False,False,True
249,E010,Kiran Nair,HR,26.0,Female,05-10-2023,37.0,4,NaN,43000.0,True,False,False,True,False

In [ ]:
# Question 4:-Normalisation (Min-Max_Scaling)
# Normalize the following columns:
# Salary
# Hours_Worked_Per_Week
# Use MinMaxScaler and display results.

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
scaler_mm = MinMaxScaler()
df[['Salary_norm','Hours_Worked_norm']]=scaler_mm.fit_transform(
    df[['Salary','Hours_Worked_Per_Week']]
)

In [15]:
print(df[['Salary','Salary_norm','Hours_Worked_Per_Week','Hours_Worked_norm']].head())

    Salary  Salary_norm  Hours_Worked_Per_Week  Hours_Worked_norm
0  50000.0     0.347826                   40.0           0.285714
1  45000.0     0.130435                   38.0           0.142857
2  60000.0     0.782609                   45.0           0.642857
3  52000.0     0.434783                    NaN                NaN
4      NaN          NaN                   50.0           1.000000

In [ ]:
# Question 5:- Standardization (Scaling)
# Apply StandardScaler on:
# Age
# Projects_Completed
# Display the transformed values.

In [9]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler_std=StandardScaler()
df[['Age_std','Projects_Completed_std']]=scaler_std.fit_transform(
    df[['Age','Projects_Completed']]
)

In [22]:
print(df[['Age','Age_std','Projects_Completed','Projects_Completed_std']].head())

    Age   Age_std  Projects_Completed  Projects_Completed_std
0  25.0 -1.140068                   5               -0.211604
1  30.0 -0.024784                   4               -0.916949
2   NaN       NaN                   6                0.493742
3  28.0 -0.470898                   5               -0.211604
4  35.0  1.090500                   7                1.199088

In [ ]:
# Question 6:-Compare Scaling Methods
# Apply both:
# MinMaxScaler
# StandardScaler
# On the Salary Column.
# Show both results side by side

In [26]:
df_temp=df[['Salary']].copy()

mm_scaler=MinMaxScaler()
std_scaler=StandardScaler()

df_temp['Salary_MinMax']=mm_scaler.fit_transform(df_temp[['Salary']])
df_temp['Salary_Standard']=std_scaler.fit_transform(df_temp[['Salary']])

In [27]:
print(df_temp.head())

    Salary  Salary_MinMax  Salary_Standard
0  50000.0       0.347826        -0.092450
1  45000.0       0.130435        -0.785825
2  60000.0       0.782609         1.294300
3  52000.0       0.434783         0.184900
4      NaN            NaN              NaN

In [ ]:
# Question 7:-Build Preprocessing Pipeline
# Create a pipeline that:
# Applies encoding to categorical columns
# Applies scaling to numerical columns
# Use:
# ColumnTransformer
# Pipeline

In [ ]:
# Reloading original df to avoid interference from Q2-Q6

In [5]:
df=pd.read_csv('employee_productivity_dataset.csv')

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [7]:
import sklearn
print(sklearn.__version__)

1.7.2

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
# Define column pipeline: impute + scale

numeric_transform = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
 ])

In [25]:
num_cols=['Age','Salary','Hours_Worked_Per_Week','Projects_Completed','Performance_Score']
cat_cols=['Gender','Departemnt','Work_Mode','Location']

In [ ]:
# WE WILL CHECK THE THE NUMERICAL COLUMNS AS WELL AS CATEGORICAL COLUMNS

In [25]:
print('Numrical_Columns',num_cols)
print('Categorical_Columns',cat_cols)

Numrical_Columns ['Age', 'Salary', 'Hours_Worked_Per_Week', 'Projects_Completed', 'Performance_Score']
Categorical_Columns ['Gender', 'Departemnt', 'Work_Mode', 'Location']

In [ ]:
# Create a pipeline for numeric columns
# Handel missing values with median.then standardize.

In [28]:
numeric_transformer=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='medium')),
    ('scaler',StandardScaler())
])

In [ ]:
# Create a pipeline for categorical columns
# Handel missing values with most frequent,then one-hot encode.drop='first' avoids dummy vaiable trap.

In [30]:
categorical_transformer=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequently')),
    ('onehot',OneHotEncoder(drop='first',handle_unknown='ignore'))
])

In [ ]:
# Combine them with ColumnTransformer
# the full processing pipeline.

In [32]:
from sklearn.compose import ColumnTransformer

In [29]:
preprocessor=ColumnTransformer(
    transformers=[
        ('num',numeric_transformer,num_cols),
        ('cat',categorical_transformer,cat_cols)
    ]
)

In [ ]:
# Question 8:- Apply Pipeline
# Apply the pipeline on the dataset
# Display:
# Transformed dataset
# Shape of final dataset

In [ ]:
# Apply the Pipline to the Dataset
# Fit and transform the data
# fit_transform learns the imputation means/ medians,scaling parameters,and categories from your data
# then applies the transformations.

In [10]:
import pandas as pd

In [13]:
df=pd.read_csv('employee_productivity_dataset.csv')
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

In [21]:
# define sub-pipelines

numeric_transformer=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

categorical_transformer=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(drop='first',sparse_output=False,handle_unknown='ignore'))
])

In [30]:
# Combine them
from sklearn.compose import ColumnTransformer
preprocessor= ColumnTransformer(
    transformers=[
        ('num',numeric_transformer,num_cols),
        ('cat',categorical_transformer,cat_cols)
    ]
)

In [31]:
# this line is what makes fir_transformer work

pipeline=Pipeline(steps=[('preprocessor',preprocessor)])

In [32]:
print(type(pipeline))
print(pipeline)

<class 'sklearn.pipeline.Pipeline'>
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'Salary',
                                                   'Hours_Worked_Per_Week',
                                                   'Projects_Completed',
                                                   'Performance_Score']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Gender', 'Departemnt',
                                                   'Work_Mode',
                                                   'Location'])]))])

In [33]:
df

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune
...,...,...,...,...,...,...,...,...,...,...,...,...
245,E006,Neha Singh,HR,27.0,Female,Remote,01-06-2023,36.0,3,3.9,42000.0,Mumbai
246,E007,Rahul Das,Finance,40.0,Male,Onsite,07-07-2019,48.0,8,4.7,65000.0,Delhi
247,E008,Pooja Mehta,Marketing,29.0,Female,Hybrid,12-08-2022,42.0,6,4.3,48000.0,Bangalore
248,E009,Sameer Khan,IT,31.0,Male,Remote,30-09-2021,NaN,5,4.1,51000.0,Pune
249,E010,Kiran Nair,HR,26.0,Female,Onsite,05-10-2023,37.0,4,NaN,43000.0,Mumbai

In [ ]:
# Question 9:- Conceptual Question:-
# Why scaling is important in python?

In [ ]:
# Scaling is important because:

 1. Many ML algorithems like KNN , SVM ,Neural Network , and Gradient Descent are sensitive to feature magnitude. 

 A feature with range 1000-50000 will dominate a feature with 0-1.

 2. Scaling helps moels coverage faster during training.

 3. It ensures all features contribute equally to distance calculations and loss functions.

 4. Without caling,coefficient in linear models become hard to interpret.

In [ ]:
# Question 10:- Conceptual Question
# Why do we convert categorical data into numerical form?

In [ ]:
# A: ML Models work only with numbers. Converting Categorical data to numerical form allows:

1 Algorithms to performs mathematical operations and find patterns.
    
2 Label Encoding for ordinal data where order matters,e.g, Low=0,Medium-1,High=2.

3 One-Hot Encoding for nominal data where no order exists,e.g,Color,Country. This avoids creating false ordinal relationships.

4 Models like Logistic Regression, SVM, and Neural Networks require numerical input.